#include <iostream>
#include <cstdlib>  // includes rand() and other functions from the C standard library  
#include <ctime>    // includes functions that return time 

using namespace std;
/* look in the standard library at the function int rand ( void ); 
    http://www.cplusplus.com/reference/clibrary/cstdlib/rand/
    
	Generates random number
	Returns a pseudo-random integer number in the range 0 to 
	RAND_MAX.

	RAND_MAX is a constant defined in <cstdlib>. 

	Its default value may vary between implementations 
	but it is granted to be at least 32767.
    */

int main()
{
  string answer;
 /* initialize the seed for the random number generator algorithm
  the seed determines the sequence of random numbers generated by rand()

  if you don't change the seed, then the program will always generate the same 
  sequence of random nunumbers
  */

srand ( time(NULL) ); // assigns current time to the random seed

cout << "RAND_MAX constant values is " << RAND_MAX << endl;
						 
for (int i = 0; i < 10; i ++)
    cout << rand() << '\t';
cout << "\nQ1: What is the output of rand() " << endl;
answer = "" ; // write your answer to Q1 in between " "
cout << "Answer Q1: " << answer << endl;

cout << endl;
for (int i = 0; i < 10; i ++)
    cout << rand()%5 << '\t';
cout << "\nQ2: What is the output of rand()%5 " << endl;
answer = "" ; // write your answer to Q2 in between " "
cout << "Answer Q2: " << answer << endl;

cout << endl;
for (int i = 0; i < 10; i ++)
    cout << rand()%5+3 << '\t';
cout << "\nQ3: What is the output of rand()%5+3 " << endl;
answer = "" ; // write your answer to Q3 in between " "
cout << "Answer Q3: " << answer << endl;	
}	
