name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run
      run: ./hello
    - name: ls
      run: ls -al
    - name: pwd
      run: pwd
    - name: cd1
      run: cd ../
    - name: ls2
      run: ls -al
    - name: cd2
      run: cd lab1-sdoboli 
    - name: clean
      run: make clean
