name: C/C++ CI  

on:
 workflow_dispatch:
     branches: [ master ]
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_dice
      run: cd Dice
           make
           ./dice_game
           make clean
           cd ..
    - name: make_team
      run: cd Team 
           make
           ./team
           make clean
           cd ..
    - name: make_money
      run: cd Money
           make
           ./test_classes
           make clean
           cd ..

    
