name: C/C++ CI  

on:
 workflow_dispatch:
     branches: [ master ]
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_game
      run: cd Deck_Cards; make; ./card_game; cd ..
    - name: make_test 
      run: cd Deck_Cards; make; ./test_deck; make clean; cd ..
     
      
      
