name: C/C++ CI  

on:
 workflow_dispatch:
     branches: [ master ]
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_all
      run: make
    - name: run_midterm
      run: ./midterm
      run: make clean
    
