name: C/C++ CI  

on:
 workflow_dispatch:
     branches: [ master ]
 # push:
 #   branches: [ master ]
 # pull_request:
 #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_pointers
      run: cd Pointers; make; ./pointers; make clean; cd ..
    - name: make_money_account
      run: cd Money_Account; make; ./test_classes; make clean; cd ..

    
