name: C/C++ CI  

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_all
      run: make
    - name: run_static
      run: ./static
    - name: run_dice
      run: ./dice
    - name: run_param
      run: ./param

    - name: clean
      run: make clean
    
